### ISSUE TITLE
Contribute

### ISSUE THREAD

**Issue by kabakakao** [Hymian7/Zebra2#5]
Hello,
I am searching for a music sheets archive for many years now. Your sounds really promising and is exactly what I am searching for. For now, I have no knowledge in programming .net, but I would like to contribute. Can you give me a simple „onboarding“ what I have to install to compile it?

**Comment by Hymian7** [comment]
Hi,
thanks for reaching out! I believe you had the same issue as I had, I was not able to find a practical sheet music archive myself either. That is why I tried to create one myself. Please note that my solution is nowhere near production ready at the moment and I haven't really found the time to properly work on in it in the last months. Anyways, the vision is still on and I would be glad if you would join to contribute.

Here are the steps to compile and run the solution:

1. Install the .NET SDK 6.0 from https://dotnet.microsoft.com/en-us/download/visual-studio-sdks
2. Clone Repo (e.g. via Git)
3. From the Subfolder "ZebraDesktop" run command 'dotnet run' in your preferred shell. All the required dependencies will be downloaded then and the GUI should show up.
4. Create a Folder (e.g. on your Desktop) for all the Zebra Files. You need 1 subfolder called "archive", 1 subfolder called "temp" and 1 empty file called database.db.
6. Create new Config via Datei->Neue Konfiguration with SQLite and Local Archive. Copy the respective paths of the archive subfolder, the temp subfolder and the database.db file into the textboxes
7. Load the config via Datei->Konfiguration laden and then you should be able to play around.

I just checked the process and I am not sure if it works 100% outside of my personal computer. Let me know if it works for you and I will double check next week if the process works on any PC.

**Comment by kabakakao** [comment]
I changed the configs path to mine. Now, the config file was created, but the error is the same and the app crashes

**Comment by kabakakao** [comment]
Now I copied the configs path to the path, where the last error searches the configs. Now I got a prompt to select my config. But after I selected the only one in the conig, I got the following error:

Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at ZebraDesktop.ViewModels.ConfigSelectorViewModel.CloseWindow(Window window) in C:\Users\Telahr\Documents\github\Zebra2\ZebraDesktop\ViewModels\ConfigSelectorViewModel.cs:line 134
   at ZebraDesktop.ViewModels.ConfigSelectorViewModel.ExecuteLoadConfigCommand(Object obj) in C:\Users\Telahr\Documents\github\Zebra2\ZebraDesktop\ViewModels\ConfigSelectorViewModel.cs:line 92
   at ZebraDesktop.ViewModels.DelegateCommand.Execute(Object parameter) in C:\Users\Telahr\Documents\github\Zebra2\ZebraDesktop\ViewModels\DelegateCommand.cs:line 37
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at ZebraDesktop.ViewModels.MainWindowViewModel.LoadConfig() in C:\Users\Telahr\Documents\github\Zebra2\ZebraDesktop\ViewModels\MainWindowViewModel.cs:line 289
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run()
   at ZebraDesktop.App.Main()

**Comment by Hymian7** [comment]
I got the same error with the NullReferenceException earlier, I'm not sure when this part broke. I will have a look at it on Monday and try to fix it.

**Comment by Hymian7** [comment]
Hi again,
I've had a look into the issues and I think I could fix all the startup problems for now. If you want to you can try again cloning the current master branch and setup the program.

To use the import function, make sure you have Pdftk installed. You can either install it via winget with `winget install PDFLabs.PDFtk.Free` or download the free version on their homepage (https://www.pdflabs.com/tools/pdftk-the-pdf-toolkit/)

Let me know if you have any other errors or problems. You can also ping me via Telegram (t.me/Hymian)

**Comment by kabakakao** [comment]
Everything is working now. Thanks for the support
